install: bundle install
before_script:
  - sudo apt-get -y install tree
  - tree ./vendor/bundle
  - which bundle
  - bundle config
  - bundle env
script: bundle exec rspec
rvm:
  - 2.4.2
  - jruby-head
  - ruby-head
